# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxBluetooth' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'RxSwift',     '~> 4.0.0-beta.1'
pod 'RxCocoa',     '~> 4.0.0-beta.1'
pod 'RxDataSources', '~> 3.0.0-beta.1'

  target 'RxBluetoothTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxBluetoothUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
